- Cargo.lock
- Cargo.toml
- README.md
- src/kbs2/backend.rs
- src/kbs2/config.rs
- src/kbs2/session.rs
- src/main.rs
Adds support for "rage-lib" as a backend, avoiding the need to shell out to either the `age` or `rage` CLIs.
An unscientific benchmark shows a roughly 6x speedup on a store containing 200 or so secrets:
With `age-backend = "rage"`:
```bash
$ time ./target/release/kbs2 list -d > /dev/null
real	0m0.595s
user	0m0.366s
sys	0m0.198s
```
With `"rage-lib"`:
```bash
$ time ./target/release/kbs2 list -d > /dev/null
real	0m0.110s
user	0m0.101s
sys	0m0.008s
```
(Debug builds show a significant slowdown with `rage-lib`, presumably because the combinator library used by `rage` benefits extensively from optimizations).
Closes #2.
> treewide: Allow the age crate (rage) to be used as a backend

- Cargo.lock
- Cargo.toml
- src/kbs2/command.rs
- src/kbs2/config.rs
- src/kbs2/generator.rs
- src/kbs2/input.rs
- src/kbs2/mod.rs
- src/kbs2/util.rs
- src/main.rs
Adds support for two kinds of generators: "internal" and "command".
"internal" generators use their configured alphabet and length to
produce a random secret, while "command" generators execute a
command (with optional arguments) and retain its output as the
secret.
Closes #8.
> treewide: Support for sensitive field generation

- src/kbs2/command.rs
- src/kbs2/config.rs
Adds three new hooks, all specific to `kbs2 pass`:
* pre-hook: Run before the record is retrieved
* post-hook: Run after the password is printed/copied
* clear-hook: Run after the clipboard is cleared (if cleared)
Closes #18.
> kbs2: Hooks for `kbs2 pass`

- Cargo.lock
- Cargo.toml
- README.md
- src/kbs2/backend.rs
- src/kbs2/command.rs
- src/kbs2/config.rs
- src/kbs2/error.rs
- src/kbs2/session.rs
- src/kbs2/util.rs
- src/main.rs
This is an experimental approach to #23, using a POSIX shared memory object to persist the unwrapped private key. Currently, only the `RageLib` backend supports wrapped keys -- all others return an error if decryption with a wrapped key is requested.
Notes:
* Needs `create_wrapped_keypair` for `trait Backend`, so that the default can be changed to a wrapped key
* Needs `kbs2 unlock` and `kbs2 lock` to expose the master authentication/session expiry steps
* Maybe: A fallback from failure to access a pinentry-compatible interface for the password prompt
* Maybe: `kbs2 wrap` to automate the process of wrapping an already present key
Closes #23.
> Wrapped key support

- src/kbs2/command.rs
- src/main.rs
This doesn't undo the current generation behavior in terse mode; that'll be removed as I more generally refactor the way input is done.
Closes #28.
> kbs2: Add `kbs2 generate`

- README.md
- src/main.rs
Commands like:
```bash
$ kbs2 new environment foo
```
are now:
```bash
$ kbs2 new -k environment foo
```
`-k`, `--kind` defaults to `login`, so `kbs2 new foo` is now a shorthand for the (old) `kbs2 new login foo`.
This makes `kbs2 new` more consistent with `kbs2 list` and makes (bash) tab completion for `kbs2 new` more useful.
> `kbs2 new`: Replace `kind` positional with option

- src/kbs2/backend.rs
- src/kbs2/record.rs
- src/kbs2/session.rs
Adds unit tests for `RageLib`, refactors `Backend` more generally
to avoid the need to repeatedly pass config objects.
See #10.
> kbs2: Backend unit tests, refactoring

- src/main.rs
This establishes the following precedence:
* `--config-dir DIR`
* `KBS2_CONFIG_DIR`
* The default, i.e. `~/.config/kbs2`
This has the nice consequence of ensuring that custom subcommands use the right configuration directory when invoking `kbs2` on their own without requiring them to do something ugly like:
```bash
$ kbs2 -c "${KBS2_CONFIG_DIR}" whatever -a -b -c
```
Hooks are not guaranteed to receive `KBS2_CONFIG_DIR` in their environment. This probably needs to be fixed and will require a more involved change (since a `Config` doesn't know the directory that produced it).
> kbs2: Use KBS2_CONFIG_DIR as a default config dir value

- src/kbs2/config.rs
- src/kbs2/session.rs
> kbs2: Hooks receive KBS2_CONFIG_DIR in their environment

- src/kbs2/config.rs
- src/kbs2/util.rs
> kbs2: Truncate the shm name to make macOS happy

- README.md
Hey,
I'm an [Arch Linux](https://aur.archlinux.org) package [maintainer](https://github.com/orhun/PKGBUILDs). I'm submitting this PR to let you know that I created the following packages for the installation of `kbs2` on Arch Linux and other distributions that support installing packages from [AUR](https://wiki.archlinux.org/index.php/Arch_User_Repository):
* [kbs2](https://aur.archlinux.org/packages/kbs2/) (builds from source)
* [kbs2-git](https://aur.archlinux.org/packages/kbs2-git/) (VCS/development package)
I also updated README.md about installation from AUR. (b943689) (resolves #77)
PS: I can also create a `-bin` package if you provide a pre-compiled x86_64 binary along with the release artifacts.
BR,
orhun.
> README: Add AUR package instructions

- src/kbs2/backend.rs
- src/kbs2/command.rs
- src/kbs2/config.rs
`Backend::create_wrapped_keypair` now takes the `SecretString` that it should wrap with, instead of using `util::get_password` to directly prompt for it.
Config initialization now takes an `Option<SecretString>` instead of a `bool` to indicate the creation of a wrapped keypair.
> refactor: Better separate interactive and backend components

- src/kbs2/agent.rs
- src/kbs2/command.rs
Allows us to separate agent initialization from running, which
makes it possible to print the former's error(s) before daemonizing.
> refactor(agent): agent::run -> Agent::run

- CHANGELOG.md
- README.md
- src/kbs2/command.rs
- src/kbs2/config.rs
- src/main.rs
This was always possible after the fact, but exposing it via the CLI makes it simpler.
> `kbs2 init`: Support setting the store dir

- .github/workflows/ci.yml
- src/kbs2/agent.rs
- src/kbs2/command.rs
- src/kbs2/config.rs
- src/kbs2/session.rs
- src/kbs2/util.rs
- src/main.rs
Bans any un-annotated uses of `unwrap`/`expect`/`panic` from the codebase, and reviews + annotates all of the current ones.
> kbs2: Forbid unwrap/expect/panic

- CHANGELOG.md
- README.md
- src/kbs2/agent.rs
- src/kbs2/backend.rs
- src/kbs2/command.rs
- src/kbs2/config.rs
- src/kbs2/record.rs
- src/main.rs
> `kbs2 rekey`

- CHANGELOG.md
- README.md
- src/kbs2/command.rs
- src/main.rs
This allows users to batch what would otherwise be multiple `kbs2 dump`
invocations into a single invocation, making things slightly simpler
and faster.
It's most useful in conjunction with the `--json` flag, since
`kbs2 dump` will emit one JSON record per line (and tools like
`jq` natively understand JSONL).
> `kbs2 dump`: allow multiple records 

- CHANGELOG.md
- src/kbs2/agent.rs
- src/kbs2/backend.rs
- src/kbs2/command.rs
Adds protocol versioning to the agent, and refactors the key management per the notes in #187.
Closes #187.
> Refactor the agent

- CHANGELOG.md
- README.md
- src/kbs2/command.rs
- src/main.rs
Allows scripts to check whether the agent has a keypair for the
current config. This is intended primarily as a plumbing command,
allowing users to query before performing any `kbs2` operations
that might block on user input or interaction.
> kbs2: add `kbs2 agent query`

- src/main.rs
Without this, the error message would literally be "{} failed: terminated by signal" with curly braces in it instead of the command that failed.
> Fix missing fmt argument in error message

- CHANGELOG.md
- README.md
- src/kbs2/config.rs
`kbs2` now prefers `config.toml` over `kbs2.conf`.
The primary motivation for this change is the config editing experience: more editors will correctly detect TOML syntax when the filename ends in `.toml` than `.conf`.
> README, src: change default config file

- CHANGELOG.md
- README.md
- src/kbs2/config.rs
- src/kbs2/generator.rs
- src/kbs2/session.rs
Refactors "internal" generators to make them both more flexible and capable of generating better secrets.
The old behavior is preserved for backwards compatibility.
> src: refactor generators

- CHANGELOG.md
- README.md
- contrib/ext-cmds/kbs2-choose-pass/kbs2-choose-pass
- contrib/ext-cmds/kbs2-dmenu-pass/kbs2-dmenu-pass
- contrib/ext-cmds/kbs2-snip/kbs2-snip
- src/kbs2/command.rs
- src/main.rs
This avoids the dance that external commands need to do to discover the config file and parse it on their own.
> src: add `kbs2 config dump`

- src/kbs2/agent.rs
Currently when trying to build on Android (using Termux) it fails because auth_client cannot be found. This fixes that problem
> Allow compiling on Android (Termux)

- CHANGELOG.md
- src/kbs2/command.rs
This should enable the use of cli editors when using `kbs2 edit` so it should fix the first part of #434
> Fix `kbs2 edit`

- contrib/ext-cmds/kbs2-qr/kbs2-qr
Improves the error message presented when `kbs2 qr` is handed a nonexistent login record (or a record that isn't a login).
> kbs2-qr: fail gracefully when record doesn't exist

- .github/workflows/zizmor.yml
- Cargo.lock
- Cargo.toml
- src/kbs2/agent.rs
- src/kbs2/backend.rs
- src/kbs2/command.rs
- src/kbs2/config.rs
- src/kbs2/record.rs
- src/kbs2/session.rs
- src/kbs2/util.rs
- src/main.rs
Bumps the dependencies, fixes API changes that occurred with `age` primarily. The big thing is that I've dropped the top-level dependency on `secrecy` and have moved to using `age`'s re-export, since that should avoid a lot of type mismatch pain in the future.
> chore: CI, deps cleanup
