src/kbs2/backend.rs

kbs2/backend: Better encrypt/decrypt errors

---

Cargo.lock
Cargo.toml
src/kbs2/command.rs
src/kbs2/config.rs
src/main.rs

treewide: Add `kbs2 edit`

---

src/kbs2/config.rs

This is pretty ugly, but ensures that we never have a lingering
invalid shared memory object.
Fixes #31.

kbs2/config: Always remove shared memory object on error

---

src/kbs2/util.rs

kbs2/util: Add unit tests

---

src/kbs2/config.rs

kbs2/config: Add unit tests

---

src/kbs2/generator.rs

kbs2/generator: Add unit tests

---

src/kbs2/record.rs

kbs2/record: Add unit tests

---

.github/workflows/ci.yml
src/kbs2/command.rs
src/kbs2/config.rs
src/kbs2/input.rs

workflows/ci: Run clippy in the CI

---

src/kbs2/backend.rs
src/kbs2/session.rs

kbs2: Add session unit tests

---

.github/workflows/release.yml

github/workflows: Add release workflow

---

Cargo.toml
README.md
src/kbs2/command.rs
src/kbs2/config.rs
src/kbs2/mod.rs
src/kbs2/session.rs
src/kbs2/util.rs

Incomplete, needs more follow-up work.
See #51.

Initial crate documentation

---

src/kbs2/backend.rs
src/kbs2/command.rs
src/kbs2/generator.rs
src/kbs2/input.rs
src/kbs2/record.rs

kbs2: Fill in more docs

---

README.md
contrib/README.md
contrib/ext-cmds/kbs2-audit-pass/kbs2-audit-pass
contrib/ext-cmds/kbs2-dmenu-pass/kbs2-dmenu-pass
contrib/ext-cmds/kbs2-kbsecret-env-import/kbs2-kbsecret-env-import
contrib/ext-cmds/kbs2-kbsecret-login-import/kbs2-kbsecret-login-import
contrib/ext-cmds/kbs2-qr/kbs2-qr
contrib/ext-cmds/kbs2-snip/kbs2-snip
contrib/ext-cmds/kbs2-yad-login/kbs2-yad-login

This replaces the kbs2-ext-cmds repository.

treewide: Add a contrib folder

---

Cargo.lock
Cargo.toml
README.md
src/kbs2/backend.rs
src/kbs2/command.rs
src/kbs2/config.rs

treewide: Keyfile dependent shm name

---

README.md
src/kbs2/command.rs
src/kbs2/config.rs
src/kbs2/input.rs

README, src: Add "generate-on-empty" behavior to `kbs2 new`

---

README.md
src/kbs2/command.rs

This took way more effort than it should have.
Closes #3.

kbs2/command: Add X11 primary clipboard support

---

README.md
src/kbs2/agent.rs
src/kbs2/backend.rs
src/kbs2/command.rs
src/kbs2/util.rs
src/main.rs

feat: `kbs2 rewrap`

---

README.md
src/kbs2/command.rs
src/kbs2/config.rs
src/kbs2/session.rs
src/kbs2/util.rs

feat: Allow the user to configure their pinentry binary

---

src/kbs2/agent.rs
src/kbs2/backend.rs
src/kbs2/config.rs
src/kbs2/util.rs

Now that wrapping and unwrapping are better encapsulated, we can actually test them.

tests: More backend tests

---

README.md
src/kbs2/config.rs
src/kbs2/session.rs
src/main.rs

feat: support for error-hook

---

CHANGELOG.md
README.md
src/kbs2/agent.rs
src/kbs2/config.rs
src/kbs2/session.rs

feat: have the kbs2 agent auto-start on session creation

---

contrib/ext-cmds/kbs2-ssh-add/README.md
contrib/ext-cmds/kbs2-ssh-add/kbs2-ssh-add

contrib: add kbs2-ssh-add

---

contrib/ext-cmds/kbs2-gpg-add/README.md
contrib/ext-cmds/kbs2-gpg-add/kbs2-gpg-add

contrib: add kbs2-gpg-add

---

CHANGELOG.md
README.md
src/kbs2/command.rs

kbs2/command: make `kbs2 list` and `kbs2 dump` more Unix friendly

---

contrib/ext-cmds/kbs2-choose-pass/README.md
contrib/ext-cmds/kbs2-choose-pass/kbs2-choose-pass
contrib/ext-cmds/kbs2-dmenu-pass/README.md
contrib/ext-cmds/kbs2-dmenu-pass/kbs2-dmenu-pass

contrib/ext-cmds: teach password choosers to show usernames

---

CHANGELOG.md
README.md
contrib/ext-cmds/kbs2-yad-login/kbs2-yad-login
src/kbs2/config.rs
src/kbs2/input.rs

kbs2: add commands.new.default-username

---

Cargo.lock
Cargo.toml
src/kbs2/command.rs
src/kbs2/config.rs
src/main.rs

treewide: unbreak clap API usage

---

CHANGELOG.md
README.md
src/kbs2/command.rs
src/kbs2/config.rs
src/kbs2/generator.rs
src/kbs2/input.rs
src/kbs2/session.rs
src/kbs2/util.rs

These were always a bit clunky, and not a great interface.

Remove "external" generators

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
src/kbs2/command.rs
src/kbs2/config.rs
src/kbs2/session.rs
src/main.rs

Adds a `kbs2 rename` subcommand, which does what it sounds like it does.

CLI: `kbs2 rename`

---

src/kbs2/agent.rs

Some mild factoring, in preparation for a larger set of agent improvements.

agent: mild cleanup

---

Cargo.lock
Cargo.toml
src/kbs2/command.rs
src/kbs2/config.rs

Unmaintained, replaced by Rust stdlib.

remove atty dep

---

CHANGELOG.md
src/kbs2/agent.rs

agent: remove unused import
